### ISSUE TITLE
How do we change the output size of the Sprites

### ISSUE THREAD

**Issue by emmalevesque** [pwrstudio/eyebeam-frontend#5]
I'm wondering if it's possible to manually set the size of the sprites that appear for projects on the map. Uploading our new sprites at 400x400px makes them appear quite large large on the map (see image below)

![Screenshot of Trust x Eyebeam App](https://i.ibb.co/rZZjCk0/Screen-Shot-2021-02-09-at-12-09-06.jpg)

**Comment by pwrstudio** [comment]
@emmalevesque ah yes, I forgot that the game elements are scaled up by 2. If it works for you I would suggest uploading the project Sprites at half of the size you want them. 

Regarding the issue you had previously with the spritesheet generation: I think the problem there was in fact an error on my part – the code creating the the spritesheet (running on the gameserver) didn't wait properly until the file(s) were fully transfered from the CMS before starting the generation. I hadn't noticed before because the files were quite small, but with bigger files the transfer time was longer, etc... I made a quick fix now and will look at it further during the day. Let me know any issues you run into here!
